const String appName = 'password_manager';
const String appVersion = '0.8.7';

const Map<String, String> defaultSettings = {
  'theme': 'dark',
  'lang': 'zh',
};

const Map<String, Map<String, String>> defaultColorThemes = {
  'green': {
    'name': '绿色',
    'bg_color': '#0D1117',
    'card_color': '#1A2E1F',
    'primary_color': '#238636',
    'accent_color': '#58A6FF',
    'danger_color': '#F85149',
    'text_color': '#C9D1D9',
    'subtext_color': '#8B949E',
  },
  'blue': {
    'name': '蓝色',
    'bg_color': '#0D1117',
    'card_color': '#1A2533',
    'primary_color': '#58A6FF',
    'accent_color': '#238636',
    'danger_color': '#F85149',
    'text_color': '#C9D1D9',
    'subtext_color': '#8B949E',
  },
  'red': {
    'name': '红色',
    'bg_color': '#0D1117',
    'card_color': '#331A1A',
    'primary_color': '#F85149',
    'accent_color': '#58A6FF',
    'danger_color': '#DA3633',
    'text_color': '#C9D1D9',
    'subtext_color': '#8B949E',
  },
  'purple': {
    'name': '紫色',
    'bg_color': '#0D1117',
    'card_color': '#2D1A33',
    'primary_color': '#A371F7',
    'accent_color': '#238636',
    'danger_color': '#F85149',
    'text_color': '#C9D1D9',
    'subtext_color': '#8B949E',
  },
};

const Map<String, String> defaultLightColors = {
  'bg_color': '#F5F5F5',
  'card_color': '#FFFFFF',
  'primary_color': '#1976D2',
  'accent_color': '#388E3C',
  'danger_color': '#D32F2F',
  'text_color': '#212121',
  'subtext_color': '#757575',
};

const Map<String, String> defaultDarkColors = {
  'bg_color': '#0D1117',
  'card_color': '#161B22',
  'primary_color': '#58A6FF',
  'accent_color': '#238636',
  'danger_color': '#F85149',
  'text_color': '#C9D1D9',
  'subtext_color': '#8B949E',
};

const Map<String, Map<String, String>> defaultLanguages = {
  'zh': {
    'name': '中文',
    'app_name': '密码管理器',
    'search_hint': '搜索密码...',
    'no_passwords': '暂无密码记录',
    'add_hint': '点击下方按钮添加',
    'settings': '设置',
    'theme': '主题',
    'dark': '暗黑',
    'light': '明亮',
    'follow_system': '跟随系统',
    'language': '语言',
    'export': '导出密码本',
    'import': '导入密码本',
    'add_password': '添加密码',
    'edit_password': '编辑密码',
    'cancel': '取消',
    'save': '保存',
    'delete': '删除',
    'confirm_delete': '确认删除',
    'delete_message': '确定要删除吗？此操作不可恢复。',
    'close': '关闭',
    'edit': '编辑',
    'account': '账号',
    'password': '密码',
    'notes': '备注',
    'name_field': '名称 *',
    'account_field': '账号',
    'password_field': '密码',
    'notes_field': '备注',
    'version': '版本',
    'copied': '已复制',
    'export_success': '导出成功',
    'export_failed': '导出失败',
    'import_success': '导入成功',
    'import_failed': '导入失败',
    'select_file': '选择文件',
    'import_mode': '导入模式',
    'direct_add': '直接添加',
    'direct_add_desc': '将JSON中的所有密码直接添加到现有密码中',
    'update_add': '更新添加',
    'update_add_desc': '对于重名密码使用JSON中的数据更新',
    'diff_add': '差异添加',
    'diff_add_desc': '只导入JSON中与现有密码不重名的项目',
    'overwrite_add': '完全覆盖',
    'overwrite_add_desc': '删除所有现有密码，完全使用JSON中的密码',
    'select_import_mode': '选择导入模式',
    'duplicates_found': '发现',
    'confirm': '确认',
    'select_storage_folder': '选择存储文件夹',
    'storage_hint': '您的数据将保存在: Documents/PasswordManager/',
    'error': '错误',
    'storage_error': '无法访问所选文件夹，请选择其他位置',
  },
  'en': {
    'name': 'English',
    'app_name': 'Password Manager',
    'search_hint': 'Search passwords...',
    'no_passwords': 'No password records',
    'add_hint': 'Tap the button below to add',
    'settings': 'Settings',
    'theme': 'Theme',
    'dark': 'Dark',
    'light': 'Light',
    'follow_system': 'Follow System',
    'language': 'Language',
    'export': 'Export Passwords',
    'import': 'Import Passwords',
    'add_password': 'Add Password',
    'edit_password': 'Edit Password',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'confirm_delete': 'Confirm Delete',
    'delete_message': 'Are you sure you want to delete? This cannot be undone.',
    'close': 'Close',
    'edit': 'Edit',
    'account': 'Account',
    'password': 'Password',
    'notes': 'Notes',
    'name_field': 'Name *',
    'account_field': 'Account',
    'password_field': 'Password',
    'notes_field': 'Notes',
    'version': 'Version',
    'copied': 'Copied',
    'export_success': 'Export Success',
    'export_failed': 'Export Failed',
    'import_success': 'Import Success',
    'import_failed': 'Import Failed',
    'select_file': 'Select File',
    'import_mode': 'Import Mode',
    'direct_add': 'Direct Add',
    'direct_add_desc': 'Add all passwords from JSON to existing passwords',
    'update_add': 'Update Add',
    'update_add_desc': 'Update existing passwords with same names from JSON',
    'diff_add': 'Difference Add',
    'diff_add_desc': 'Only import passwords from JSON that don\'t conflict',
    'overwrite_add': 'Overwrite All',
    'overwrite_add_desc': 'Delete all existing passwords and use only passwords from JSON',
    'select_import_mode': 'Select Import Mode',
    'duplicates_found': 'Found',
    'confirm': 'Confirm',
    'select_storage_folder': 'Select Storage Folder',
    'storage_hint': 'Your data will be saved to: Documents/PasswordManager/',
    'error': 'Error',
    'storage_error': 'Cannot access selected folder, please choose another location',
  },
};